/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;

import com.entidades.Libros;
import com.entidades.Prestamo;
import com.entidades.Usuarios;
import java.text.DateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;
import util.HibernateUtil;

/**
 *
 * @author Deysi
 */
public class frmPrestamo extends javax.swing.JDialog {

    DateFormat fecha=DateFormat.getDateInstance();
    /**
     * Creates new form frmPrestamo
     */
    public frmPrestamo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        hibernateSession();
        arranque();
    }
    
    private Session st;
    private DefaultTableModel model;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        panel1 = new org.edisoncor.gui.panel.Panel();
        labelCustom1 = new org.edisoncor.gui.label.LabelCustom();
        labelCustom2 = new org.edisoncor.gui.label.LabelCustom();
        labelCustom3 = new org.edisoncor.gui.label.LabelCustom();
        labelCustom4 = new org.edisoncor.gui.label.LabelCustom();
        labelCustom5 = new org.edisoncor.gui.label.LabelCustom();
        cblibro = new org.edisoncor.gui.comboBox.ComboBoxRound();
        cbusuario = new org.edisoncor.gui.comboBox.ComboBoxRound();
        labelCustom6 = new org.edisoncor.gui.label.LabelCustom();
        txtid = new org.edisoncor.gui.textField.TextField();
        txtsalida = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtmaxima = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txtdevolucion = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelNice2 = new org.edisoncor.gui.panel.PanelNice();
        btnguardar = new org.edisoncor.gui.button.ButtonTask();
        btnnuevo = new org.edisoncor.gui.button.ButtonTask();
        btneditar = new org.edisoncor.gui.button.ButtonTask();
        btncancelar = new org.edisoncor.gui.button.ButtonTask();
        btneliminar = new org.edisoncor.gui.button.ButtonTask();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelNice1.setBackground(new java.awt.Color(0, 0, 0));

        panel1.setColorPrimario(new java.awt.Color(255, 255, 255));

        labelCustom1.setBackground(new java.awt.Color(204, 255, 255));
        labelCustom1.setText("Libro:");

        labelCustom2.setBackground(new java.awt.Color(204, 255, 255));
        labelCustom2.setText("Usuario:");

        labelCustom3.setBackground(new java.awt.Color(204, 255, 255));
        labelCustom3.setText("Fecha Salida:");

        labelCustom4.setBackground(new java.awt.Color(204, 255, 255));
        labelCustom4.setText("Fecha Maxima:");

        labelCustom5.setBackground(new java.awt.Color(204, 255, 255));
        labelCustom5.setText("Fecha Devolucion:");

        labelCustom6.setBackground(new java.awt.Color(204, 255, 255));
        labelCustom6.setText("ID:");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(labelCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(labelCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtmaxima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCustom3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(labelCustom1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCustom2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cblibro, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(cbusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                        .addGap(27, 27, 27))
                                    .addComponent(labelCustom6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(txtsalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cblibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCustom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Libro", "Usuario", "Salida", "Maxima", "Devolucion"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        panelNice2.setBackground(new java.awt.Color(255, 255, 255));

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/1399150686_stock_save-as.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setDescription("Save");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/1399150686_stock_save-as.png"))); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.setDescription("New");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/1399150821_27-Edit Text.png"))); // NOI18N
        btneditar.setText("Editar");
        btneditar.setDescription("Edit");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/1399150921_Cancel.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setDescription("Cancel");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/1399150857_Close_Box_Red.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setDescription("Delete");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNice2Layout = new javax.swing.GroupLayout(panelNice2);
        panelNice2.setLayout(panelNice2Layout);
        panelNice2Layout.setHorizontalGroup(
            panelNice2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice2Layout.createSequentialGroup()
                .addGroup(panelNice2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNice2Layout.createSequentialGroup()
                        .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNice2Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNice2Layout.setVerticalGroup(
            panelNice2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNice2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelNice1Layout = new javax.swing.GroupLayout(panelNice1);
        panelNice1.setLayout(panelNice1Layout);
        panelNice1Layout.setHorizontalGroup(
            panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNice1Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNice1Layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNice1Layout.createSequentialGroup()
                        .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelNice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))))
        );
        panelNice1Layout.setVerticalGroup(
            panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        nuevo();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        guardarUno();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
        editar();
    }//GEN-LAST:event_btneditarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        arranque();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        eliminar();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        retornarPrestamo();
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPrestamo dialog = new frmPrestamo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void hibernateSession(){
    st = HibernateUtil.getSessionFactory().openSession();
}
    
    private void arranque(){
    cargarCombo2();
    cargarCombo();
    
      
    this.txtid .setEnabled(false);
    this.txtid.setText(null);
    this.cblibro.setEnabled(false);
    this.cblibro.setSelectedIndex(-1);
    this.cbusuario.setEnabled(false);
    this.cbusuario.setSelectedIndex(-1);
    this.txtsalida.setEnabled(false);
    this.txtsalida.setText(null);
    this.txtmaxima.setEnabled(false);
    this.txtmaxima.setText(null);
    this.txtdevolucion.setEnabled(false);
    this.txtdevolucion.setText(null);
   
    this.btnguardar.setEnabled(false);
    this.btneditar.setEnabled(false);
    this.btneliminar.setEnabled(false);
    this.btnnuevo.setEnabled(true);
    this.btnguardar.setText("Guardar");
    this.jTable1.setEnabled(true);
    tableModel();
    cargarTabla();
}
    
    public void tableModel(){
    this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(15);
    this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(20);
    this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
    this.jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
    model = (DefaultTableModel)this.jTable1.getModel();
    model.setNumRows(0);
}
    public void cargarCombo(){
    this.cblibro.removeAllItems();
    List<Libros> lista = (List<Libros>)st.createQuery("From Libros").list();
    for(Libros tipoList : lista){
        this.cblibro.addItem(tipoList.getNombre());            
    }
    
    
}
    
    public void cargarCombo2(){
    this.cbusuario.removeAllItems();
    List<Usuarios> lista = (List<Usuarios>)st.createQuery("From Usuarios").list();
    for(Usuarios tipoList : lista){
        this.cbusuario.addItem(tipoList.getNombre());            
    }
}
    
    public void cargarTabla(){
    List<Prestamo> lista = (List<Prestamo>)st.createQuery("From Prestamo").list();
    for(Prestamo presta : lista){
        model.addRow(new Object[]{

                presta.getIdprestamo(),presta.getIdlibro(),presta.getIdusuario(),presta.getFechaSalida(),presta.getFechaMaxima(),presta.getFechaDevolucion()
                
        });
    }
}
    
    public void nuevo(){
    this.cblibro.setSelectedIndex(-1);
    this.cblibro.setEnabled(true);
     this.cbusuario.setSelectedIndex(-1);
    this.cbusuario.setEnabled(true);
    this.txtsalida.setText(null);
    this.txtsalida.setEnabled(true);
    this.txtmaxima.setText(null);
    this.txtmaxima.setEnabled(true);
    this.txtdevolucion.setText(null);
    this.txtdevolucion.setEnabled(true);
    this.btnguardar.setEnabled(true); 
    this.txtid.setText("Auto");
}
public void guardarUno(){
    if(this.txtsalida.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Falta Prestamo salida");
    }
    else{
        if((this.cblibro.getSelectedIndex()==-1) || (this.cbusuario.getSelectedIndex()==-1 || (this.txtsalida.getText().isEmpty())|| (this.txtmaxima.getText().isEmpty())||(this.txtdevolucion.getText().isEmpty()) )){
           this.cblibro.setSelectedIndex(-1);
           this.cbusuario.setSelectedIndex(-1);
           this.txtsalida.setText("-");
           this.txtmaxima.setText("-");
           this.txtdevolucion.setText("-");
     
           guardarDos();
        }
        else{
          guardarDos();  
        }
        
    }
}

public void guardarDos(){
    if(this.btnguardar.getText().equals("Guardar")){
       st.beginTransaction();
       Prestamo li = new Prestamo();
       Object selectedItem = this.cblibro.getSelectedItem();
      Libros retornoTipo = retornoTipo(selectedItem.toString());
       Object selectedItem1 = this.cbusuario.getSelectedItem();
      Usuarios retornoTipo1 = retornoTipo1(selectedItem1.toString());
      li.setIdlibro(retornoTipo);
      li.setIdusuario(retornoTipo1);
       li.setFechaSalida(this.txtsalida.getText());
       li.setFechaMaxima(this.txtmaxima.getText());
       li.setFechaDevolucion(this.txtdevolucion.getText());
  
       st.save(li);
       st.update(retornoTipo);
       st.update(retornoTipo1);
       st.getTransaction().commit();
       JOptionPane.showMessageDialog(null, "Registro de Libros guardado.");
       cargarTabla();
       arranque();
    }
    else{
       st.beginTransaction();
       int selectedRow = this.jTable1.getSelectedRow();
       int idli = Integer.parseInt(String.valueOf(model.getValueAt(selectedRow, 0)));
       Prestamo li = (Prestamo)st.load(Prestamo.class, idli);
        Object selectedItem = this.cblibro.getSelectedItem();
      Libros retornoTipo = retornoTipo(selectedItem.toString());
       Object selectedItem1 = this.cbusuario.getSelectedItem();
      Usuarios retornoTipo1 = retornoTipo1(selectedItem1.toString());
      li.setIdlibro(retornoTipo);
      li.setIdusuario(retornoTipo1);
       li.setFechaSalida(this.txtsalida.getText());
       li.setFechaMaxima(this.txtmaxima.getText());
       li.setFechaDevolucion(this.txtdevolucion.getText());
       st.update(li);
       st.update(retornoTipo);
       st.update(retornoTipo1);
       st.getTransaction().commit();
      JOptionPane.showMessageDialog(null, "Registro de Libros actualizado.");
      cargarTabla();
      arranque();
    } 
}

    public Libros retornoTipo(String desT){
    Libros tipRet = null;
    String desTipo = desT;
    try {
        Query query = st.createQuery("From Libros t Where t. nombre = ?");
        query.setParameter(0, desTipo);
        try {
            tipRet = (Libros)query.uniqueResult();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hay más Libros de tipo: " + desTipo);
        }
        
    } catch (Exception e) {
        
    }
    return tipRet;
}
    
    
   
    public Usuarios retornoTipo1(String desT){
    Usuarios tipRet = null;
    String desTipo = desT;
    try {
        Query query = st.createQuery("From Usuarios t Where t. nombre = ?");
        query.setParameter(0, desTipo);
        try {
            tipRet = (Usuarios)query.uniqueResult();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hay más Usuarios de tipo: " + desTipo);
        }
        
    } catch (Exception e) {
        
    }
    return tipRet;
}
   
    
    
    public void retornarPrestamo(){
    if(this.jTable1.isEnabled()){
        int selectedRow = this.jTable1.getSelectedRow();
        Object valueAt = model.getValueAt(selectedRow, 0);
        int idp = Integer.parseInt(valueAt.toString());
        Prestamo art = (Prestamo)st.load(Prestamo.class, idp);
        this.txtid.setText(String.valueOf(art.getIdprestamo()));
        
        this.cblibro.setSelectedItem(art.getIdlibro().getNombre());
         this.cbusuario.setSelectedItem(art.getIdusuario().getNombre());
        this.txtsalida.setText(String.valueOf(art.getFechaSalida()));
        this.txtmaxima.setText(String.valueOf(art.getFechaMaxima()));
        this.txtdevolucion.setText(String.valueOf(art.getFechaDevolucion()));
        
        this.btneditar.setEnabled(true);
        this.btneliminar.setEnabled(true);
        this.btnnuevo.setEnabled(false);
    }    
}
    public void editar(){
    
    this.cblibro.setEnabled(true);
    this.cbusuario.setEnabled(true);
    this.txtsalida.setEnabled(true);
   this.txtmaxima.setEnabled(true);
   this.txtdevolucion.setEnabled(true);
    this.btnguardar.setEnabled(true); 
    this.btnguardar.setText("Actualizar");
    this.jTable1.setEnabled(false);
    this.btneliminar.setEnabled(false);
}
    
    public void eliminar(){
   int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Eliminación de Registro", "Desea eliminar este registro.", JOptionPane.YES_NO_OPTION);
   if(showConfirmDialog == 1){
       JOptionPane.showMessageDialog(null, "Registro no eliminado.");
   }
   else{
       st.beginTransaction();
       int selectedRow = this.jTable1.getSelectedRow();
       Object valueAt = model.getValueAt(selectedRow, 0);
       int idp = Integer.parseInt(valueAt.toString());
       Prestamo p = (Prestamo)st.load(Prestamo.class, idp);
       st.delete(p);
       st.getTransaction().commit();
       JOptionPane.showMessageDialog(null, "Registro eliminado.");
       arranque();
   }
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTask btncancelar;
    private org.edisoncor.gui.button.ButtonTask btneditar;
    private org.edisoncor.gui.button.ButtonTask btneliminar;
    private org.edisoncor.gui.button.ButtonTask btnguardar;
    private org.edisoncor.gui.button.ButtonTask btnnuevo;
    private org.edisoncor.gui.comboBox.ComboBoxRound cblibro;
    private org.edisoncor.gui.comboBox.ComboBoxRound cbusuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.edisoncor.gui.label.LabelCustom labelCustom1;
    private org.edisoncor.gui.label.LabelCustom labelCustom2;
    private org.edisoncor.gui.label.LabelCustom labelCustom3;
    private org.edisoncor.gui.label.LabelCustom labelCustom4;
    private org.edisoncor.gui.label.LabelCustom labelCustom5;
    private org.edisoncor.gui.label.LabelCustom labelCustom6;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    private org.edisoncor.gui.panel.PanelNice panelNice2;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtdevolucion;
    private org.edisoncor.gui.textField.TextField txtid;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtmaxima;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtsalida;
    // End of variables declaration//GEN-END:variables
}
