/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;

import javax.swing.ImageIcon;


public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
       
        //Arrancar maximizado el formulario
        setExtendedState(MAXIMIZED_BOTH);
        //Especificar un icono para la aplicación: "png" "jpg" 
        setIconImage(new ImageIcon(ClassLoader.getSystemResource("com/img/li.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmsalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmusuario = new javax.swing.JMenuItem();
        jmlibro = new javax.swing.JMenuItem();
        jmprestamo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setMaximumSize(new java.awt.Dimension(375, 375));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/1399279053_archive.png"))); // NOI18N
        jMenu1.setText("Archivo");

        jmsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/1399150857_Close_Box_Red.png"))); // NOI18N
        jmsalir.setText("Salir");
        jmsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmsalirActionPerformed(evt);
            }
        });
        jMenu1.add(jmsalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/1399279087_catalog.png"))); // NOI18N
        jMenu2.setText("Catalogo");

        jmusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/1399266453_edit_group.png"))); // NOI18N
        jmusuario.setText("Usuarios");
        jmusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmusuarioActionPerformed(evt);
            }
        });
        jMenu2.add(jmusuario);

        jmlibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/1399266433_books.png"))); // NOI18N
        jmlibro.setText("Libros");
        jmlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlibroActionPerformed(evt);
            }
        });
        jMenu2.add(jmlibro);

        jmprestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/1399266480_Bank.png"))); // NOI18N
        jmprestamo.setText("Prestamos");
        jmprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmprestamoActionPerformed(evt);
            }
        });
        jMenu2.add(jmprestamo);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/li.png"))); // NOI18N
        jMenu3.setText("Grupo de trabajo");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmusuarioActionPerformed
        // TODO add your handling code here:
        frmUsuarios c = new frmUsuarios(this, true);
        c.setVisible(true);
        
    }//GEN-LAST:event_jmusuarioActionPerformed

    private void jmlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlibroActionPerformed
        // TODO add your handling code here:
        frmLibros c = new frmLibros(this, true);
        c.setVisible(true);
        
    }//GEN-LAST:event_jmlibroActionPerformed

    private void jmsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmsalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jmsalirActionPerformed

    private void jmprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmprestamoActionPerformed
        // TODO add your handling code here:
        frmPrestamo c = new frmPrestamo(this, true);
        c.setVisible(true);
               
    }//GEN-LAST:event_jmprestamoActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        Aboutme2 about = new Aboutme2(this, true);
        about.setVisible(true);
               
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmlibro;
    private javax.swing.JMenuItem jmprestamo;
    private javax.swing.JMenuItem jmsalir;
    private javax.swing.JMenuItem jmusuario;
    // End of variables declaration//GEN-END:variables
}
